#!/bin/bash

#
# makes sure that ocropus compiles !
#
# Responsible: kofler
#

# include common functions (look there for documentation!)
. `dirname $0`/common.sh

# make sure we are in the right directory
verifyDir

section TEST-RUN
# actually run ocropus
verifyCommand "cd ocroscript/scripts" 0
export OCROSCRIPTS=`pwd` 
verifyCommand "../ocroscript recognize ../../data/pages/alice_1.png" 0
exit $?
