#! /bin/sh

if [ $# = 0 ]; then
    echo usage: $0 "<directory>/version.cc" 1>&2
    exit
fi

export VERSION_STAMP="`svnversion -n` `date +%Y-%m-%d` `uname -o -i`"

cat << EOF > $1
// Generated by generate_version_cc.sh
const char *hardcoded_version_string() {
    return "$VERSION_STAMP";
}
EOF
